# Site settings
title:          Develop Log
description:    "noihaus develop log"
url:            https://noihaus.github.io

# Author
author:
  name:         noihaus
  email:        sky2174@gmail.com
  url:          https://github.com/noihaus

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: sky2174@gmail.com
  github: https://github.com/noihaus
  linkedin: https://www.linkedin.com/in/kyungsik-yoo-334162130/
